# Generated by Django 5.2.5 on 2025-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('show_add_button', models.BooleanField(default=True, verbose_name='Показывать кнопку «Добавить»')),
                ('require_login_to_add', models.BooleanField(default=False, verbose_name='Добавлять могут только админы')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
    ]
